version: '3'
services:
  db:
    image: postgres:10.1
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: contacts_db