INSERT INTO public.attachments (persons_id, filename, comments, loaddate) VALUES (1, 'homework.java', 'Home Work on Java courses', '2018-09-25');
INSERT INTO public.attachments (persons_id, filename, comments, loaddate) VALUES (1, 'homework.sql', 'Home Work on Java courses sql file', '2018-09-25');
INSERT INTO public.attachments (persons_id, filename, comments, loaddate) VALUES (2, 'movie.mp4', 'Moive43', '2018-09-25');
INSERT INTO public.attachments (persons_id, filename, comments, loaddate) VALUES (2, 'photo.jpg', 'Some photos by trip', '2018-09-25');
INSERT INTO public.attachments (persons_id, filename, comments, loaddate) VALUES (3, 'music.mp3', 'Music I like', '2018-09-25');
INSERT INTO public.attachments (persons_id, filename, comments, loaddate) VALUES (3, 'readme.txt', 'readme file for project', '2018-09-25');
INSERT INTO public.attachments (persons_id, filename, comments, loaddate) VALUES (3, 'calc.java', 'Calculator implemented on Java', '2018-09-25');
INSERT INTO public.attachments (persons_id, filename, comments, loaddate) VALUES (4, 'HeadFirst.pdf', 'Book, yet dont know about what', '2018-09-25');
INSERT INTO public.attachments (persons_id, filename, comments, loaddate) VALUES (4, 'notVirus.exe', 'Exactly not a virus. Trust me, Im an engineer', '2018-09-25');
INSERT INTO public.attachments (persons_id, filename, comments, loaddate) VALUES (4, 'notVirus2.exe', 'Trust me again. Let it run by admin permissions', '2018-09-25');