version: '3'
services:
    myapp:
        image: baymuratorazov/myapp:prod.back
        ports:
            - 1234:8080
        links:
            - db
    frontend: 
        image: baymuratorazov/myapp:prod.front
        ports: 
            - 80:80
        links:
            - myapp
    db:
        image: postgres:10.1
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: postgres
            POSTGRES_DB: contacts_db     